src/queue.rs
The virtio tests use a SomeplaceInMemory struct which is pretty much a duplicate of `vm_memory::VolatileRef`, let's drop it to avoid duplication and to provide a realistic example of how to use `VolatileMemory`/`VolatileSlice`/`VolatileRef`.
=>  Replace SomePlaceInMemory with VolatileRef

src/device.rs
We want to use the eventfd module.
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
=> device: Fix vmm_sys_util import

coverage_config_aarch64.json, coverage_config_x86_64.json, src/queue.rs
Make `Descriptor` a public API strict, and turn `DescriptorChain` into an Iterator that returns them.  This is more efficient because it avoids cloning of the `GuestMemory` whenever a descriptor is created, and it is a better API that prevents the list from being accessed more than once. Consumers can still store the Descriptors in a vec if desirable.
=> Make DescriptorChain an Iterator

Cargo.toml, coverage_config_aarch64.json, coverage_config_x86_64.json, src/lib.rs, src/queue.rs
This patch set includes:
1) some minor bugfixes
2) port EVENT_IDX from cloud hypervisor
3) port readable/writable iterator from cloud hypervisor
4) port indirect descriptoer from cloud hypervisor
5) reduce unused dependency on epoll
This is a patch set split out from #13 , and #13 will only includes GuestMemory related changes.
=> Enhancement to the virtio queue

coverage_config_aarch64.json, coverage_config_x86_64.json, src/queue.rs
Implement Queue::index() to fix #20 and fix a bug in getting the has_next flag.
=> Implement Queue::index() and Queue::has_next()

Cargo.toml, benches/main.rs, benches/queue/mock.rs, benches/queue/mod.rs, coverage_config_x86_64.json, src/queue.rs
Hi all! This PR proposes two additions. The first is a `criterion`-based benchmark that mainly exercises descriptor chain iteration (for now :D). That commit is also adding a bunch of functionality that mocks and helps populate `Queue` contents. I've later realized we also had something like that as part of the unit test functionality; going forward, it would be great to unify the auxiliary logic. The benchmark can be started using something like `cargo bench --bench main`.
The second commit proposes some simplifications related to descriptor chain handling, mostly by unifying the handling of descriptors from the initial and indirect tables. Other changes include:
- `DescriptorChain::has_next` has been removed, as its semantics were a bit unclear and didn't seem very useful (it can return …
=> Simple initial benchmark and descriptor handling simplifications

src/queue.rs
Add setter/getter for `Queue::next_avail` and derive Clone for `DescriptorChain`. These changes enable crates such as `vhost-user-backend` and `vhost-user-fs` to start using this crate.
=> Add setter/getter for Queue::next_avail and derive Clone for DescriptorChain

Cargo.toml, benches/queue/mod.rs, coverage_config_x86_64.json, src/queue.rs
This PR switches to using version `0.3.0` of `vm-memory` which adds atomic `load` and `store` support as part of the `Bytes`/`GuestMemory` interface. There are also some proposed changes around the notification logic (for example, double checking when enabling notifications to make sure we don't miss one), as well as more comments just in case they are helpful to people reading the code (there's one example around enabling notifications that should be turned into a doc comment/example for consumers of the crate, because it's not  immediately clear what the use pattern looks like).
Also, I was wondering if it makes sense to remove `DescriptorChainRwIter` and the related logic, because it looks like we can achieve the same by calling `filter()` on `DescriptorChain` when iterating. WDYT?
=> Switch to latest vm-memory and tweak the notification logic

Cargo.toml
Replace the strict =0.4.6 with the more relaxed >=0.4.6 which matches
vhost-user-backend and so then crate can be combined with a repository
that uses a newer version of log such as cloud-hypervisor.
Signed-off-by: Rob Bradford <robert.bradford@intel.com>
=> build: Relax dependency on log

Cargo.toml, coverage_config_x86_64.json, src/block/defs.rs, src/block/mod.rs, src/block/request.rs, src/block/stdio_executor.rs
- added discard, write zeroes and get device id requests
- added a method to StdIoBackend that processes the request execution result, by writing the status byte to memory and returning the number of bytes written to memory. For now, this method assumes that if writing to memory in `execute` method fails, no bytes were written to memory, which is not necessarily true. Will add in a subsequent PR/commit a logic that handles partial writing too.
+ some other fixes
Also, from a high level view over #33, looks like the entire `block` module could benefit in the future from the Reader and Writer wrappers and we can switch to using them here too, once they get merged.
=> block: add support for the rest of requests

src/block/stdio_executor.rs, src/device/virtio_config.rs, src/lib.rs, src/queue.rs
This PR:
* Derives `Debug` for a few types that were missing them. Also adds a manual implementation for `DescriptorChainRwIter`, because Rust doesn't seem to be able to generate the `M::T: Debug` constraint
* Adds `#![warn(missing_debug_implementations)]`, so we don't regress with missing Debug implementations in the future
* Derive Clone for DescriptorChainRwIter. This is useful in vhost-user-scsi: the virtio-scsi response includes some metadata at the beginning, so it's convenient to write the beginning of the response last. I accomplish this by cloning the DescriptorChainRwIter (or, actually, a higher-level wrapper), skipping forward past the header, writing the body; then using the original DescriptorChainRwIter to write the header.
=> Add some missing trait implementations.

crates/devices/virtio-blk/src/request.rs, crates/virtio-queue/benches/queue/mock.rs, crates/virtio-queue/src/defs.rs, crates/virtio-queue/src/lib.rs
This is similar to virtio-blk, which already has a dedicated constant definitions module.
My only question is whether to make some of the constants `pub(crate)`, more specifically the ones that define sizes (VIRTQ_AVAIL_ELEMENT_SIZE, etc), as they are only used in virtio-queue crate at the moment.
=> Move virtio-queue constant definitions to a dedicated module

crates/devices/virtio-blk/src/request.rs, crates/virtio-queue/benches/queue/mod.rs, crates/virtio-queue/src/lib.rs, crates/virtio-queue/src/mock.rs
Closes #72.
This PR tries to merge the two interfaces that are used for mocking the driver side of virtio queue operations: the one used for unit tests and the one used for benchmarks.
=> Unify virtio-queue mocking code

crates/virtio-device/src/mmio.rs, crates/virtio-device/src/virtio_config.rs, crates/virtio-queue/src/lib.rs
Moves specification-required checks to setters
Moves the mandatory checks, according to the virtio specification,
from Queue::is_valid() to the corresponding Queue setters.
closes: #94
Signed-off-by: German Maglione <gmaglione@redhat.com>
=> Moves specification-required checks to setters

coverage_config_x86_64.json, crates/devices/virtio-blk/src/request.rs, crates/virtio-queue/src/lib.rs, crates/virtio-queue/src/mock.rs
This PR simplifies the `QueueState` abstraction by removing the generic type parameter `M`, and also relaxes the trait bounds for `AvailIter` and `Descriptor` chain to not depend on `GuestAddressSpace` anymore, as the logic within is only interested in `M` dereferencing to something that implements `GuestMemory` (and not also in the part that it might be one of the associated type of a `GuestAddressSpace` implementation).
=> Remove generic type parameter `M` from `QueueState`

coverage_config_x86_64.json, crates/virtio-queue/src/lib.rs, crates/virtio-queue/src/queue.rs, crates/virtio-queue/src/queue_guard.rs, crates/virtio-queue/src/state.rs, crates/virtio-queue/src/state_sync.rs
The last two patches tries to:
1) convert `enum QueueStateGuard` to `trait QueueStateGuard` for extensibility and zero-cost abstraction.
2) introduce "struct QueueGuard` to encapsulate a QueueStateGuard object and associated guest memory object.
=> Refine QueueStateGuard and introduce QueueGuard

crates/virtio-queue/src/descriptor.rs, crates/virtio-queue/src/iterator.rs, crates/virtio-queue/src/queue.rs, crates/virtio-queue/src/state.rs, crates/virtio-queue/src/state_sync.rs
This is an attempt at fixing support for big-endian architectures by:
- Stating that `Descriptor` and `VirtqUsedElem` fields are stored with little-endian ordering.
- Transforming from to little-endian in their respective `new` methods, and from little-endian on their accessors.
- Ensuring we're always using the accessors to read the fields.
- Doing endianess conversions when reading/writing individual values from/to memory.
The `::from_le` and `::to_le` methods are no-ops on little-endian machines, so their introduction shouldn't have any impact on those architectures.
I'm marking this PR as a draft, as I don't think it makes sense to merge it until we've reached a final decision about the API change in https://github.com/rust-vmm/vm-virtio/pull/111
=> Fix support for big-endian architectures

crates/virtio-queue/Cargo.toml
The virito-queue crate should licensed by either Apache 2.0 or
BSD-3-Clause.
Signed-off-by: Liu Jiang <gerry@linux.alibaba.com>
=> queue: fix license for publishing v0.1.0

coverage_config_x86_64.json, crates/virtio-queue/src/lib.rs, crates/virtio-queue/src/queue.rs, crates/virtio-queue/src/queue_guard.rs, crates/virtio-queue/src/state.rs, crates/virtio-queue/src/state_sync.rs
These helpers are meant to help crate's consumers getting and setting
information about the queue.
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
=> virtio-queue: Add helpers for accessing queue information

crates/virtio-queue/src/queue_guard.rs, crates/virtio-queue/src/state.rs
Fix `QueueState::used_idx` and `test_queue_guard_object` on s390x (endianess issues).
=> Fix `QueueState::used_idx` and `test_queue_guard_object` on s390x (endianess issues).

coverage_config_x86_64.json, crates/devices/virtio-vsock/Cargo.toml, crates/devices/virtio-vsock/src/lib.rs, crates/devices/virtio-vsock/src/packet.rs
This PR is adding an implementation of the vsock packet, based on the design proposal from https://github.com/rust-vmm/vm-virtio/issues/128. The documentation is in a decent shape already, but I will open a separate PR with some improvements to it and also code examples.
Open questions:
1. Do we want to have an upper limit for the data array size? I didn't add one yet, cloud-hypervisor and firecracker are using [the one defined in the linux kernel](https://elixir.bootlin.com/linux/v4.9.12/source/include/linux/virtio_vsock.h#L14). Do we assume this one to be a good enough limit for a vsock driver?
2. On the TX path, should we go with the `len` from the header for the data array size or do we keep the one from the data descriptor? I'll think a bit more about this.
=> add VsockPacket implementation

crates/virtio-queue/CHANGELOG.md, crates/virtio-queue/src/lib.rs, crates/virtio-queue/src/state.rs, crates/virtio-queue/src/state_sync.rs
1) Remove `#[derive(Clone)]` for `QueueState`.
2) Add method `size()` to `QueueStateT`.
requirements:
test.
=> Minor refinement to QueueState and QueueStateT

Cargo.toml, crates/virtio-queue-ser/Cargo.toml, crates/virtio-queue-ser/src/lib.rs, crates/virtio-queue-ser/src/state.rs, crates/virtio-queue/src/state.rs
Based on the design agreed [here](https://github.com/rust-vmm/community/pull/118) (and similar to what is already done in vm-superio), created a new crate, virtio-queue-ser, and added QueueStateSer. Once we have a fix for https://github.com/rust-vmm/vm-virtio/issues/143, this PR will probably need some updates, but high level it should remain the same. Marking this as draft until that.
requirements:
test.
=> add QueueStateSer

crates/virtio-queue/src/iterator.rs, crates/virtio-queue/src/lib.rs, crates/virtio-queue/src/queue.rs, crates/virtio-queue/src/queue_guard.rs, crates/virtio-queue/src/state.rs, crates/virtio-queue/src/state_sync.rs
This RFC suggests a solution addressing the shortcomings mentioned in #144 (there are some very small orthogonal changes that got through as well). Not sure if the choice of naming for the new trait is the best, but the approach is to use that to explicitly gate operations that are only safe/sane when we know for sure accesses are not performed in a multi-threaded context.
=> Improve the usability of queue interfaces

crates/virtio-queue-ser/src/state.rs, crates/virtio-queue/src/queue.rs, crates/virtio-queue/src/state.rs, crates/virtio-queue/src/state_sync.rs
This PR proposes an improvement to the efficiency of storing state and executing functionality related to the `needs_notification` queue logic. It replaces the current `signalled_used: Option<Wrapping<u16>>` member of the state structure with a `num_added: Wrapping<u16>` (which keeps track of how many descriptor chains have been added to the used ring since the last call to `needs_notification`), and also simplifies the logic in `needs_notification`.
A similar approach is used in the Linux virtio code as well (one example can be found [here](https://elixir.bootlin.com/linux/v5.15.35/source/drivers/virtio/virtio_ring.c#L661)). It appears to bring noticeable performance improvements in use cases where `needs_notification` calls constitute an increased proportion of the overall budget …
=> [RFC] Improve the efficiency of `needs_notification` for queues

crates/virtio-queue/README.md, crates/virtio-queue/src/state.rs
Did a few fixes before publishing virtio-queue 0.3.0.
requirements:
test.
=> virtio-queue: small fixes to docs

crates/virtio-queue/CHANGELOG.md, crates/virtio-queue/Cargo.toml
This PR contains the required updates to `Cargo.toml` and the changelog in order to publish version `0.3.0` of `virtio-queue`. ~~It also adds two license files to the `virtio-queue` subfolder, as mentioned int the crate release guidelines.~~
=> Prepare releasing virtio-queue v0.3.0

crates/virtio-queue-ser/CHANGELOG.md, crates/virtio-queue-ser/Cargo.toml, crates/virtio-queue-ser/README.md
Added changelog, initial readme, and `Cargo.toml` updates for the initial release of `virtio-queue-ser`.
=> Prepare releasing virtio-queue-ser v0.1.0

crates/devices/virtio-vsock/CHANGELOG.md, crates/devices/virtio-vsock/Cargo.toml
Created the initial changelog line and added a few small adjustments to the `Cargo.toml` file for `virtio-vsock`.
=> Prepare releasing virtio-vsock v0.1.0 

crates/virtio-queue/src/lib.rs
The `avail_idx` and `used_idx` methods panic if the ordering is not the right one. As checking the ordering incurs a performance degradation, the VMM will be responsible for calling these functions only with the right ordering. We're now making this panic explicit by adding it to the public documentation.
requirements:
test.
=> Update documentation of avail_idx & used_idx

coverage_config_x86_64.json, crates/devices/virtio-console/Cargo.toml, crates/devices/virtio-console/src/console.rs, crates/devices/virtio-console/src/lib.rs
Handles the queue chain processing for the virtio console device.
Signed-off-by: Niculae Radu <r.niculae99@gmail.com>
This is part of the virtio console implementation.
The purpose of this component is to process the queue chains and
to implement additional features (for example resize). The features
are not yet implemented. 
requirements:
test.
=> Add initial virtio console implementation

crates/devices/virtio-blk/src/stdio_executor.rs, crates/virtio-queue/src/defs.rs, crates/virtio-queue/src/iterator.rs, crates/virtio-queue/src/mock.rs, crates/virtio-queue/src/state.rs
While testing the virtio-console in vmm-reference, @RaduNiculae noticed that the vm
was no longer booting with the latest upstream. This was caused by some bugs
introduced in https://github.com/rust-vmm/vm-virtio/pull/170.
requirements:
test.
=> Fix some regressions from #170

Cargo.toml, README.md
At my company Cyberus Technology, we think about upstreaming certain functionality. As preparation and to get familiar with the code base and the contribution process, here is a first PR. It synchronizes the README with the crates of this repository and orders all crates alphabetically.
btw: I noticed that some things seem to be unmaintained or unused. For example:
- `virtio-device` is not on crates.io 
- `virtio-devices` is on crates.io but its GitHub repository doesn't exist
- `virtio-console` is not on crates.io
Any comments on those?
requirements:
test.~
=> Cleanup of README + alphabetical order of crates

crates/virtio-queue/src/lib.rs, crates/virtio-queue/src/queue.rs
The number of descriptor chain heads to process should always be smaller or equal to the queue size, as the driver should never ask the VMM to process a available ring entry more than once. Checking and reporting such incorrect driver behavior can avoid potential hanging and Denial-of-Service from VMMs.
Signed-off-by: Bo Chen <chen.bo@intel.com>
requirements:
test.
=> virtio-queue: Error out early on invalid available ring index

crates/devices/virtio-blk/Cargo.toml, crates/devices/virtio-console/Cargo.toml, crates/devices/virtio-vsock/CHANGELOG.md, crates/devices/virtio-vsock/Cargo.toml, crates/virtio-device/Cargo.toml, crates/virtio-queue-ser/CHANGELOG.md, crates/virtio-queue-ser/Cargo.toml, crates/virtio-queue/CHANGELOG.md, crates/virtio-queue/Cargo.toml, fuzz/Cargo.toml, fuzz/common/Cargo.toml
Update intra-rust-vmm dependencies to latest versions that have fixed requirements and release new versions
requirements:
test.
=> Update vm-memory, vmm-sys-util and virtio-queue + release

crates/virtio-bindings/CONTRIBUTING.md
The bindgen CLI was recently extracted to its own crate.  When I updated the bindgen version, I didn't realise the cargo installation instructions needed to be changed.
requirements:
test.
=> virtio-bindings: fix bindgen install instructions

crates/devices/virtio-console/Cargo.toml, crates/virtio-queue-ser/Cargo.toml
`cargo test` works, but due to how cargo enables features for crates built in a workspace, this is by accident, and the following commands fail without this patch:
- Fixes `cargo test -p virtio-console`
- Fixes `cargo test -p virtio-queue-ser`
These changes are modeled after the dev-dependencies that already exist to enable these features in e.g. virtio-vsock: 
https://github.com/rust-vmm/vm-virtio/blob/c527b45dada0a81d343aca7f06759d5637d6429a/crates/devices/virtio-vsock/Cargo.toml#L18-L20
requirements:
test.
- [n/a] All added/changed public-facing functionality has entries in the "Upcoming 
Release" section of CHANGELOG.md …
=> Enable features required for tests

crates/virtio-queue/CHANGELOG.md, crates/virtio-queue/src/chain.rs
see also: https://gitlab.com/virtio-fs/virtiofsd/-/issues/74
With specific guest kernel config, virtiofsd run panic with cloud-hypervisor, because address of indirect descriptor table is not proper aligned.
After read the spec, there should no restrict on address of indirect descriptor:
2.6.5 The Virtqueue Descriptor Table
...
To increase ring capacity the driver can store a table
of indirect descriptors anywhere in memory, and insert
a descriptor in main virtqueue (with
flags&VIRTQ_DESC_F_INDIRECT on) that refers to memory
buffer containing this indirect descriptor table.
requirements:
message has max 60 characters for the summary and max 75 characters …
=> virtio-queue: fix alignment check for indirect descriptor

crates/virtio-queue/src/mock.rs, crates/virtio-queue/src/queue.rs
Fix a couple of new endianess issues in the mock queue that impact big endian hosts (namely, s390x).
Signed-off-by: Sergio Lopez <slp@redhat.com>
=> virtio-queue: fix endianess issues in mock queue

crates/virtio-queue-ser/CHANGELOG.md, crates/virtio-queue-ser/Cargo.toml, crates/virtio-queue/CHANGELOG.md, crates/virtio-queue/Cargo.toml
This is a patch release that fixes endianess and the problems with the iterator. In this release we did not update to the latest virtio-bindings version as that would result in a big change. This could cause other problems that would make it hard to consume this otherwise important patch release.
Note that when building locally virtio-queue the latests virtio-bindings will be used, but in production use cases this will not be the case because the v0.1.0 virtio-bindings will be used from crates.io.
requirements:
test.
=> release virtio-queue v0.7.1

fuzz/common/src/lib.rs
We were iterating over both descriptor chains, and descriptors in a chain. This was triggering a timeout when running the fuzzer. When implementing a device though, this timeout should not happen because the device implementation must make sure to only retrieve as many descriptor chains as it needed. This cannot be addressed at the queue abstraction level.
requirements:
test.
=> fuzz: iterate only over descriptor chains

crates/virtio-queue/CHANGELOG.md, crates/virtio-queue/src/chain.rs, crates/virtio-queue/src/queue.rs
When fuzzing a SCSI vhost-user device, the fuzzer invented a (rather large) self referential descriptor. virtio-scsi then requires reporting the "residual" bytes, which when summing up the remaining bytes can overflow 2^32 bytes. Since the spec mandates that descriptor chains must not exceed 2^32 bytes, let's just terminate iteration once we overrun.
The tests demonstrate how the overflows happened before. While virtio-queue does not directly suffer from any consequences, this guards consumers from having to handle this on their own.
Link: https://rust-vmm.slack.com/archives/CFH3R8PFV/p1682002847952759
Terminate iterating over a descriptor chain that is longer than 2^32 bytes.
requirements:
message has max 60 …
=> virtio-queue: do not iterate over more than 2^32 bytes

crates/devices/virtio-blk/Cargo.toml, crates/devices/virtio-console/Cargo.toml, crates/devices/virtio-vsock/CHANGELOG.md, crates/devices/virtio-vsock/Cargo.toml, crates/virtio-bindings/CHANGELOG.md, crates/virtio-device/Cargo.toml, crates/virtio-queue-ser/CHANGELOG.md, crates/virtio-queue-ser/Cargo.toml, crates/virtio-queue/CHANGELOG.md, crates/virtio-queue/Cargo.toml, fuzz/Cargo.toml, fuzz/common/Cargo.toml
We need to update all projects at once to avoid breaking the ability to run "cargo test" from the root of the workspace.
=> Bulk update vm-memory to 0.11.0

crates/devices/virtio-console/Cargo.toml, crates/devices/virtio-vsock/CHANGELOG.md, crates/devices/virtio-vsock/Cargo.toml, crates/virtio-device/Cargo.toml, crates/virtio-queue-ser/CHANGELOG.md, crates/virtio-queue-ser/Cargo.toml, crates/virtio-queue/CHANGELOG.md, crates/virtio-queue/Cargo.toml
Set up the stage for releasing virtio-queue-0.8.0 by updating the version in the crate and all its references across the workspace.
Also get ready to release virtio-queue-ser-0.5.0, as it seems we want to always keep them in sync.
=> virtio-queue-0.8.0 and virtio-queue-ser-0.5.0

crates/devices/virtio-vsock/CHANGELOG.md, crates/devices/virtio-vsock/Cargo.toml
This updates vm-memory and virtio-queue crates to newer versions.
=> release virtio-vsock v0.3.0

crates/devices/virtio-vsock/src/packet.rs
`as_ptr()` is deprecated now and users must use `ptr_guard()` instead. Migrate to that.
requirements:
test.
=> vsock: Migrate to `ptr_guard()` for volatile slice

crates/devices/virtio-blk/Cargo.toml, crates/devices/virtio-blk/src/stdio_executor.rs, crates/devices/virtio-console/Cargo.toml, crates/devices/virtio-console/src/console.rs, crates/devices/virtio-vsock/Cargo.toml, crates/virtio-device/Cargo.toml, crates/virtio-queue-ser/Cargo.toml, crates/virtio-queue/Cargo.toml, fuzz/Cargo.toml, fuzz/common/Cargo.toml
Mostly this introduces the traits WriteVolatile and ReadVolatile. Since these can deal more efficiently deal with the volatile semantics, some old methods got deprecated.
Mostly that means replacing Read/Write with {Read,Write}Volatile.
requirements:
test.
=> Update to vm-memory 0.13.1

crates/devices/virtio-blk/src/request.rs, crates/devices/virtio-console/src/console.rs
This warning is new in latest Rust and breaks when updating the CI environment [1].
[1] https://github.com/rust-vmm/vm-virtio/pull/258
requirements:
test.
=> fix "useless-vec" clippy warning

.buildkite/custom-tests.json, fuzz/Cargo.toml, fuzz/common/Cargo.toml, fuzz/common/src/blk.rs, fuzz/common/src/lib.rs, fuzz/fuzz_targets/blk.rs
Add a new `cargo-fuzz` target to test `virtio-blk` request parsing. Add as well a simple test.
This new target mimics the existing `virtio-vsock` one in a much simpler way, as the `virtio-blk` interface is smaller.
test.
=> Add `virtio-blk` fuzzing target

crates/virtio-bindings/CHANGELOG.md, crates/virtio-bindings/src/lib.rs
Bindings for the virtio IDs were added in commit 1f2dd436, but they were never exposed to users of the crate. Do so by adding a public module.
Fixes: 1f2dd436 ("bindings: add bindings for virtio_ids.h")
requirements:
test.
=> bindings: add `virtio_ids` module

crates/devices/virtio-blk/src/stdio_executor.rs
Add three methods to retrieve the inner `B` from an `StdIoBackend`. This is useful to inspect or save the inner state of the backend object.
requirements:
test.
=> blk: add methods to retrieve the backing object from `StdIoBackend`

virtio-blk/Cargo.toml, virtio-queue-ser/Cargo.toml, virtio-queue/Cargo.toml
Hey everyone, I am propagating some dependency updates across the rust-vmm ecosystem. This one brings a fix for a security vulnerability behind feature-gated code not used by vm-virtio (the `with-serde` feature), see GHSA-875g-mfp6-g7f9, but its probably nice-to-have to prevent `cargo audit` from blocking CIs :) 
test.
=> Update vmm-sys-util to 0.12.0

coverage_config_x86_64.json, fuzz/Cargo.toml, fuzz/common/Cargo.toml, virtio-blk/Cargo.toml, virtio-console/Cargo.toml, virtio-device/Cargo.toml, virtio-queue-ser/CHANGELOG.md, virtio-queue-ser/Cargo.toml, virtio-queue/CHANGELOG.md, virtio-queue/Cargo.toml, virtio-vsock/Cargo.toml
This release contains update of dependencies used in several APIs (e.g. `vm-memory`).
`vm-memory `was just updated for dependency with `vmm-sys-util` where a security issue was fixed.
This release is blocking for https://github.com/rust-vmm/vhost/pull/220
requirements:
test.
=> Prepare virtio-queue v0.11.0 and virtio-queue-ser v0.8.0 releases

virtio-vsock/CHANGELOG.md, virtio-vsock/Cargo.toml
This release contains update of dependencies used in several APIs (e.g. vm-memory).
This is needed for `vhost-device`, where CI is failing, if we update `vm-memory` and other crates to the latest version: https://github.com/rust-vmm/vhost-device/pull/596
requirements:
test.
=> virtio-vsock: release v0.5.0

virtio-console/Cargo.toml, virtio-device/Cargo.toml, virtio-queue-ser/CHANGELOG.md, virtio-queue-ser/Cargo.toml, virtio-queue/CHANGELOG.md, virtio-queue/Cargo.toml, virtio-vsock/Cargo.toml
This release contains the new `Reader`/`Writer` classes to iterate over descriptors.
This is useful for vhost devices (see https://github.com/rust-vmm/vhost-device/pull/580).
requirements:
test.
=> Prepare the release of virtio-queue v0.12.0 and virtio-queue-ser v0.9.0

virtio-queue/src/queue.rs
The doc comment and the example of `enable_notification()` are already written at the beginning of the file. So we can remove it here.
requirements:
test.
=> virtio-queue: remove enable_notification()'s comments

Cargo.toml, fuzz/Cargo.toml, fuzz/common/Cargo.toml, virtio-blk/Cargo.toml, virtio-console/Cargo.toml, virtio-device/Cargo.toml, virtio-queue-ser/Cargo.toml, virtio-queue/Cargo.toml, virtio-vsock/Cargo.toml
- build: Centralize rust-vmm crates to workspace
- build: Update vm-memory from 0.15.0 to 0.16.0
requirements:
test.
=> build: Update vm-memory from 0.15.0 to 0.16.0

virtio-blk/src/request.rs, virtio-queue/src/descriptor_utils.rs, virtio-queue/src/queue.rs, virtio-vsock/src/packet.rs
Fixes for new minor lint warnings that cause error in CI.
Signed-off-by: Manos Pitsidianakis <manos.pitsidianakis@linaro.org>
=> New round of clippy warning fixups 

virtio-bindings/CHANGELOG.md, virtio-bindings/Cargo.toml, virtio-blk/Cargo.toml, virtio-console/Cargo.toml, virtio-queue/CHANGELOG.md, virtio-queue/Cargo.toml, virtio-vsock/CHANGELOG.md, virtio-vsock/Cargo.toml
Changed
- Regenerate bindings with Linux 6.12.
- Introduced bindgen build dependency and its clang development package dependency. See bindgen fix below for why this was necessary.
Fixed
- Add license files.
- Use bindgen library from build.rs to fix i686 builds due to x86_64-specific alignment checks.
Closes: #328
=> virtio-bindings: Prepare v0.2.5 release

virtio-queue/src/queue.rs
Our CI is being upgraded to Rust 1.85 and this will produce new warnings from clippy like this one:
```
error: this `map_or` can be simplified
--> virtio-queue/src/queue.rs:313:19
|
313 |           } else if desc_table
|  ___________________^
314 | |             .checked_add(desc_table_size)
315 | |             .map_or(true, |v| !mem.address_in_range(v))
| |_______________________________________________________^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
= note: `-D clippy::unnecessary-map-or` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::unnecessary_map_or)]`
help: use is_none_or instead
|
313 ~         } else if desc_table
314 + …
```
=> virtio-queue: fix clippy warnings on Rust 1.85

virtio-console/Cargo.toml, virtio-device/Cargo.toml, virtio-queue-ser/CHANGELOG.md, virtio-queue-ser/Cargo.toml, virtio-queue/CHANGELOG.md, virtio-queue/Cargo.toml, virtio-vsock/CHANGELOG.md, virtio-vsock/Cargo.toml
Fixed
- Add license files.
Changed
- Updated virtio-bindings from 0.2.4 to 0.2.5.
- Use `RawDescriptor` to represent the memory layout of the split and packed descriptor in virtio-queue/desc.
- Move the split descriptor to the virtio-queue/desc.
- Updated vmm-sys-util from v0.12.1 to v0.14.0
Added
- Add packed descriptor in virtio-queue
Changed
- Updated virtio-queue form 0.14.0 to 0.15.0
Fixed
- Add license files.
requirements:
test.
=> virtio-queue & virtio-queue-ser: Prepare for new release

README.md
Update README with existing Kani proofs. This PR is regarding the addition of the first proof at https://github.com/rust-vmm/vm-virtio/pull/338. I am not sure if the README shall mention the existing PRs because that will force people to keep it update. At the same time, it may be useful for users to know which requirements from the specification are proved to be conform to.
Closes: #353
requirements:
test.
=> Update README with Kani proofs
