Cargo.toml

Configure resolver = "2" in Cargo.toml

---

crates/devices/virtio-blk/Cargo.toml
crates/devices/virtio-blk/src/stdio_executor.rs
crates/virtio-device/Cargo.toml
crates/virtio-queue/Cargo.toml
crates/virtio-queue/benches/queue/mod.rs

Upgrade to the latest vm-memory v0.6 release.
Signed-off-by: Liu Jiang <gerry@linux.alibaba.com>

Upgrade to vm-memory v0.6

---

coverage_config_x86_64.json
crates/virtio-queue/src/lib.rs

This PR adds or improves tests for validating the notification suppression mechanism, the reset, indirect descriptor requirements and processing of them.

virtio-queue: improve testing

---

crates/virtio-queue/README.md
crates/virtio-queue/src/queue_guard.rs

add the License section to virtio-queue README

---

crates/devices/virtio-blk/src/request.rs
crates/virtio-queue/src/mock.rs

At Andreea's suggestion, I moved the second commit from https://github.com/rust-vmm/vm-virtio/pull/131 to make that PR (unfortunately only) a bit smaller. This PR should be merged before the packet one because it is required by the tests in that one.

move build_desc_chain to MockSplitQueue

---

CODEOWNERS

It was suggested my experience with VirtIO might be a useful addition
to the eyeballs on this repository. As such here is my application ;-)
Signed-off-by: Alex Bennée <alex.bennee@linaro.org>

CODEOWNERS: add myself as a reviewer

---

crates/virtio-queue/CHANGELOG.md

This release corrects the endianess for `used_idx` and adds some helper
functions for setting/getting fields in the queue. The later is used for
consuming the queue in Cloud Hypervisor.
requirements:
test.

release v0.2.0

---

crates/virtio-queue/Cargo.toml

I forgot to update the Cargo.toml version. This is needed so we can publish the crate.
requirements:
test.

Release v0.2.0 for virtio-queue - Update Cargo.toml

---

crates/virtio-queue/src/mock.rs

Added a new method to the mock queue that can be used to add a descriptor chain at any offset in the table. This way multiple chains can be added to the queue. This wasn't possible before with `build_desc_chain` which can add a chain only at the beginning of the descriptor table.
requirements:
test.

queue/mock: add method for adding a desc chain to the queue

---

crates/devices/virtio-vsock/src/packet.rs

Opened again a PR so that hopefully the CI won't fail again to checkout the branch.
Fixed some leftovers from https://github.com/rust-vmm/vm-virtio/pull/131. More details in the commit messages
requirements:
test.

vsock packet updates

---

crates/devices/virtio-vsock/src/packet.rs

We validate the size of the RX buffers that is corresponding to the
payload is not exceeding the maximum allowed one.
Signed-off-by: uran0sH <huangwenyuu@outlook.com>
issue: #157 
requirements:
test.

vsock: validate the size of the RX buffers

---

README.md
crates/devices/virtio-vsock/README.md
crates/devices/virtio-vsock/src/packet.rs

Added the documentation that was missing for publishing the vsock packet.
requirements:
test.

add missing documentation to the vsock packet

---

crates/devices/virtio-blk/src/request.rs
crates/devices/virtio-vsock/src/packet.rs
crates/virtio-queue/benches/queue/mod.rs
crates/virtio-queue/src/chain.rs
crates/virtio-queue/src/descriptor.rs
crates/virtio-queue/src/iterator.rs
crates/virtio-queue/src/mock.rs
crates/virtio-queue/src/queue.rs
crates/virtio-queue/src/queue_guard.rs

Add error handling
Add function called build_chain_of_descriptors
that receives a vector of Descriptor structures
and creates a chain of them.
Signed-off-by: Delia-Maria Pavel <delia_maria.pavel@stud.acs.upb.ro>
requirements:
test.

Add changes to mock.rs

---

crates/virtio-queue-ser/CHANGELOG.md
crates/virtio-queue-ser/Cargo.toml
crates/virtio-queue/CHANGELOG.md
crates/virtio-queue/Cargo.toml

This release updates the mock interface and fixes issues discovered
during fuzzing.
requirements:
test.

v0.4.0 virtio-queueue release

---

CODEOWNERS

I was providing reviews as a gatekeeper. As I got more context into
vm-virtio now, I'll add myself as an explicit code owner.
requirements:
test.

add myself as an explicit reviewer

---

crates/devices/virtio-vsock/src/packet.rs
crates/virtio-queue/CHANGELOG.md
crates/virtio-queue/Cargo.toml
crates/virtio-queue/benches/queue/mod.rs
crates/virtio-queue/src/descriptor.rs
crates/virtio-queue/src/mock.rs
crates/virtio-queue/src/queue.rs

Release the newly merged changes.
More conservative requirements for crates to avoid breaking changes on new releases.
As a follow up, we should enable dependabot for this crate as well.
requirements:
test.

Release virtio queue v0.5.0 & Update dependency Requirements

---

crates/virtio-queue/Cargo.toml

Forgot to do that in #180. Without this we cannot publish the new version.
requirements:
test.

update Cargo version to v0.5.0

---

crates/virtio-queue-ser/CHANGELOG.md
crates/virtio-queue-ser/Cargo.toml

- Update the way we are specifying dependencies as per: https://github.com/rust-vmm/community/issues/131
- Release a new version of this crate
requirements:
test.

Release virtio queue ser

---

Cargo.toml
crates/devices/virtio-blk/Cargo.toml
crates/devices/virtio-vsock/Cargo.toml
crates/virtio-device/Cargo.toml
crates/virtio-device/src/mmio.rs
crates/virtio-queue-ser/Cargo.toml
crates/virtio-queue-ser/src/state.rs
crates/virtio-queue/Cargo.toml
crates/virtio-queue/src/chain.rs
crates/virtio-queue/src/state.rs

Signed-off-by: Obei Sideg <obei.sideg@gmail.com>
Upgrade to 2021 edition
requirements:
test.

Upgrade to 2021 edition

---

crates/virtio-bindings/CONTRIBUTING.md

This was lost when virtio-bindings was imported into the vm-virtio workspace, which left generating the bindings completely undocumented.  I'm working on updating / adding to the bindings, and it was very difficult to figure out how to do that until I discovered that there had previously been documentation about it that had got lost.
requirements:
test.

virtio-bindings: re-add and update CONTRIBUTING.md

---

crates/virtio-queue/CHANGELOG.md
crates/virtio-queue/Cargo.toml

Prepare patch release 0.6.1.
Signed-off-by: Laura Loghin <lauralg@amazon.com>
requirements:
test.

release 0.6.1

---

crates/devices/virtio-vsock/CHANGELOG.md
crates/devices/virtio-vsock/Cargo.toml

This release fixes a spec violation in the vsock packet implementation.
Fixes: #210 
requirements:
test.

release virtio-vsock v0.2.1

---

README.md

- added links to fuzzing readme
- added details about how to unblock the 1 day fuzzing sessions for which we recently added support
requirements:
test.

update fuzz docs

---

crates/virtio-bindings/CHANGELOG.md

virtio-bindings: add CHANGELOG for upcoming release

---

fuzz/common/src/lib.rs

Added functions that iterate over descriptors in a loop and call the missing getter for desc_table.
requirements:
test.

Add more functions to virtio fuzz target

---

CODEOWNERS

After discussion in the rust-vmm #general on Slack, I volunteered to help publish new releases as part of our development effort for vhost-device.
requirements:
test.

Add @epilys in CODEOWNERS

---

crates/virtio-bindings/CHANGELOG.md
crates/virtio-bindings/src/virtio_config.rs
crates/virtio-bindings/src/virtio_net/generated.rs

Still on bindgen 0.63.0, because newer versions generate exactly the same thing.
requirements:
test.

virtio-bindings: regenerate with Linux 6.4

---

crates/virtio-queue/src/mock.rs

Replace a few instances of unwrap() that could cause crashes during fuzzing runs with a returned error. Introduce a new MockError variant for errors accessing guest memory.
These crashes were found with the fuzzer in #246 (e.g. https://buildkite.com/rust-vmm/vm-virtio-ci/builds/858#01890e21-2688-4fbe-a801-822f5dae4dae).
requirements:
test.

virtio-queue: fix various crashes in mock queue

---

.github/dependabot.yml

Config was copied from vhost, a866ed1d66f92a4119cdce18d767114e62948fae.
requirements:
test.

dependabot: also watch for crates.io updates

---

crates/devices/virtio-console/Cargo.toml
crates/devices/virtio-vsock/Cargo.toml
crates/virtio-device/Cargo.toml
crates/virtio-queue-ser/CHANGELOG.md
crates/virtio-queue-ser/Cargo.toml
crates/virtio-queue/CHANGELOG.md
crates/virtio-queue/Cargo.toml

Last release was borked. It should have been a major.
requirements:
- `na` All added/changed functionality has a corresponding unit/integration
test.
- `na` Any newly added `unsafe` code is properly documented.

New release of virtio-queue

---

crates/virtio-bindings/CHANGELOG.md
crates/virtio-bindings/src/virtio_net/generated.rs

Still no changes to the bindgen output from newer bindgen.
requirements:
test.

virtio-bindings: regenerate with Linux 6.6

---

virtio-bindings/CHANGELOG.md
virtio-bindings/src/virtio_net/generated.rs

Still no changes to the bindgen output from newer bindgen.
requirements:
test.

virtio-bindings: regenerate with Linux 6.10

---

virtio-queue/Cargo.toml

Make Cargo.toml reflect the Apache-2.0 AND BSD-3-Clause license. This PR is regarding to #283.
requirements:
test.

virtio_queue: fix license in Cargo.toml 

---

virtio-bindings/CHANGELOG.md
virtio-bindings/Cargo.toml
virtio-blk/Cargo.toml
virtio-console/Cargo.toml
virtio-device/Cargo.toml
virtio-queue-ser/CHANGELOG.md
virtio-queue-ser/Cargo.toml
virtio-queue/CHANGELOG.md
virtio-queue/Cargo.toml
virtio-vsock/CHANGELOG.md
virtio-vsock/Cargo.toml

- virtio-bindings: Prepare v0.2.4 release
- virtio-queue: Prepare v0.14.0 release
- virtio-queue-ser: Prepare v0.11.0 release
- virtio-vsock: Prepare v0.8.0 release
requirements:
test.

chore: Prepare release

---

virtio-bindings/CHANGELOG.md
virtio-bindings/Cargo.toml
virtio-blk/Cargo.toml
virtio-console/Cargo.toml
virtio-device/Cargo.toml
virtio-queue-ser/CHANGELOG.md
virtio-queue-ser/Cargo.toml
virtio-queue/CHANGELOG.md
virtio-queue/Cargo.toml
virtio-vsock/CHANGELOG.md
virtio-vsock/Cargo.toml

Prepare for new release of the crate and remove all the unnecessary deps and feature flags.
requirements:
test.

Remove unnecessary features and builds deps and prepare for new release
